### ISSUE TITLE
图片数据 和 .DB文件 .

### ISSUE THREAD

**Issue by 625781186** [nature1995/Vue-Django-Shop-Website#3]
Media 图片文件夹 和 你部署好的数据库 能上传一下吗  , 自己配有麻烦 ,  感谢.

![image](https://user-images.githubusercontent.com/30521429/81709478-79f70280-94a4-11ea-952a-aeda74b14c25.png)

**Comment by nature1995** [comment]
```
# 数据库选择SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
```
数据库文件在的。media文件夹已经添加，请pull一下。
